### ISSUE TITLE
Prediction using supervised learning method

### ISSUE THREAD

**Issue by benjivega** [BigData2020MasterInformatica/FinanceAnalysis#10]
Test Gradient Boosting Regressor, Bagging Regressor and Random Forest Regressor to predict some data using the APIs.

**Comment by DRTorresRuiz** [comment]
Hi @benjivega, how is this issue going? Should we close it?

**Comment by benjivega** [comment]
Hi @DRTorresRuiz.  Yes, this issue can be closed.

**Comment by DRTorresRuiz** [comment]
Great, thank you for answering! I'll close it!
