### ISSUE TITLE
Analysis for Streaming Data

### ISSUE THREAD

**Issue by leticiayepezchavez** [BigData2020MasterInformatica/FinanceAnalysis#11]
The goals are:
- The statistic analysis like mean, variance, standard desviation...
- Analize how to estimate clusters on streaming data.

**Comment by DRTorresRuiz** [comment]
First goal is duplicated in #13. Should we include it in the other issue?

**Comment by leticiayepezchavez** [comment]
The goal is an analysis in real time of the streaming data. And we think that the another issue is related to static data.

**Comment by DRTorresRuiz** [comment]
> The goal is an analysis in real time of the streaming data. And we think that the another issue is related to static data.

@leticiayepezchavez You are right, it can be thought in that way. Thus, this issue could have the topic _**Clusters on streaming data estimation**_; the #13 issue,  _**Statistical measures of static data**_; and a new issue could be titled _**Statistical measures of static data**_.  What do you think about this? 

_Do not hesitate to join us in this conversation_
