### ISSUE TITLE
Study of the most relevant companies in the technology sector and classification using historical data

### ISSUE THREAD

**Issue by FernandoGD97** [BigData2020MasterInformatica/FinanceAnalysis#21]
The next development of the project will be divided into several parts:
- Data collection and processing: We will get through the API Financial Modeling the history of several leading companies in the technology sector.
- Elaboration of a classification model: From the above data, we will develop a model to predict the closing price. 
- Visualization and analysis of the results obtained: Finally, using the results gotten we will represent to study their behavior and to be able to obtain conclusions.

**Comment by DRTorresRuiz** [comment]
Hi @FernandoGD97 @benjivega @mchuckles, I'd like to integrate #19 #22 with this issue. How do you think we can do it? Should we pass an additional argument to the `to_buy_or_not_to_buy()` function defined in #22 to allow the use of different classifiers? Since we do not have a lot of extra time, what classifiers do you think we should include?

**Comment by FernandoGD97** [comment]
Hi @DRTorresRuiz . Seeing that we are short of time, I would recommend that you indicate that you are working with time series and we with classification algorithms in this iteration. Implementing different notebooks. Anyway, the classifiers we have used are:
- Linear Regression
- Gradient Boosting Regressor
- Isotonic Regressor

**Comment by DRTorresRuiz** [comment]
> Hi @DRTorresRuiz . Seeing that we are short of time, I would recommend that you indicate that you are working with time series and we with classification algorithms in this iteration. Implementing different notebooks. Anyway, the classifiers we have used are:
> 
> * Linear Regression
> * Gradient Boosting Regressor
> * Isotonic Regressor

Thank you for answering! I'll check these algorithms and try to integrate them with #19 and #22

**Comment by DRTorresRuiz** [comment]
I have included the following classifiers in the function `to_buy_or_not_to_buy()` in #24 :

- Multilayer Perceptron
- Random Forest
- ~~Gradient-Boosted Tree~~ 

> It exits with an error when using Gradient-Boosted Tree: `Labels must be in {0,1}; note that GBTClassifier currently only supports binary classification.` 
> 
> This is because we use 0, 1 and 2 labels to classify.

- ~~LinearSVC~~

> LinearSVC only supports binary classification. 3 classes detected in LinearSVC

- Decision Tree
